name: 'Build Angular'
description: 'Build an Angular application. Intended to be used in conjunction with -deploy, and -test.'

inputs:
  repository:
    description: 'Which Angular repository are we building?'
    required: true
  app-name:
    description: 'App name. Used for param store lookups.'
    required: true
  target-environment:
    description: 'Where are we deploying this?'
    required: true
    default: 'None'
  gha-build-token:
    description: 'The GitHub Actions build token as a parameter. Typically would be BUILD_GITHUB_TOKEN'
    required: true
  build-role-dev:
    description: 'The relevant dev build role for AWS stuff.'
    required: true
  build-role-prod:
    description: 'The relevant production build role for AWS stuff.'
    required: true
  aws-access-key-id:
    description: 'AWS access key!'
    required: true
  aws-secret-access-key:
    description: 'AWS access key, but more secreter!'
    required: true
  aws-region:
    description: 'Regionality of the AWS credentialing'
    required: true
  aws-role:
    description: 'Who are we acting as with our AWS credentials?'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Build Role
      id: set-role
      uses: orthofi/actions-set-build-role@v1
      with:
        production-role: ${{ inputs.build-role-prod }}
        dev-role: ${{ inputs.build-role-dev }}
        environment-name: ${{ inputs.target-environment }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-role }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: {{ inputs.repository }}
        fetch-depth: 0

    - name: Get App Config
      uses: orthofi/actions-aws-ssm-get-by-path@v1
      with:
        paths: ${{ format('/app/{0}/env/{1}/', inputs.app_name, inputs.target-environment) }}
        save-to-environment: true
        prefix: APP_
        file: .env

    - name: Set environment name
      run: |
        echo "" >> .env
        echo "APP_ENV_NAME=$APP_ENV_NAME" >> .env

    - name: Prepare Angular
      uses: orthofi/actions-prepare-angular@v1

    - name: Build
      run: npm run build

    - name: Add build info
      uses: orthofi/actions-angular-build-info@v1

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: client
        path: dist